name: CI

on:
     push:
          branches:
               - master

jobs:
     build:
          runs-on: ${{ matrix.os }}
          strategy:
               matrix:
                    include:
                         - os: ubuntu-latest
                           arch: x64
                         - os: ubuntu-22.04
                           arch: x64
                         - os: macos-latest
                           arch: arm64
                         - os: macos-14
                           arch: x64
                         - os: windows-latest
                           arch: x64

          steps:
               - name: Checkout code
                 uses: actions/checkout@v4

               - name: Install Rust
                 uses: dtolnay/rust-toolchain@stable

               - name: Build
                 run: cargo build --release

               - name: Upload artifact
                 uses: actions/upload-artifact@v4
                 with:
                      name: ttsrs-${{ matrix.os }}-${{ matrix.arch }}
                      path: |
                           target/release/ttsrs
                           target/release/ttsrs.exe
